version: '3'

services:

    haproxy:
        image: haproxy:2.2-alpine
        ports:
            - 80:80
        expose:
            - 80
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        network_mode: "host"
